title: Lose to a Kiss
author: Peter Ilves
description: > # this means to ignore newlines until "baseurl:"
  WAKE UP. Too much to do.
baseurl: ""
twitter_username: DrPeterILVES

minima:
  date_format: "%b, %Y"

exclude:
  - README.md
  - LICENSE.txt
  - Makefile
  - .gitignore
